// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    '@nuxt/content',
    '@nuxt/eslint',
    '@nuxt/image',
    '@nuxt/ui',
    '@vueuse/nuxt',
    '@nuxtjs/sitemap',
    '@nuxtjs/robots',
    'nuxt-og-image',
  ],

  devtools: { enabled: true },

  app: {
    head: {
      titleTemplate: '%s — Neil Richter',
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
      ],
    },
  },

  css: ['~/assets/css/main.css'],

  // Canonical origin - used by @nuxtjs/sitemap, @nuxtjs/robots (sitemap
  // reference), and nuxt-og-image (absolute OG image URLs) to build
  // absolute URLs. www.nook.sh redirects to this apex at the app level
  // (server/middleware/www-redirect.ts), so this is the one true origin.
  site: {
    url: 'https://nook.sh',
  },
  compatibilityDate: '2025-07-15',

  // Deploy target: Cloudflare Workers (unified Workers+static-assets, the
  // current default Cloudflare recommends for new projects - not classic
  // "Pages"). @nuxt/content auto-detects any `cloudflare*` preset and
  // switches its database to Cloudflare D1 (binding name `DB`) regardless
  // of which cloudflare preset is used - no manual database config needed,
  // see node_modules/@nuxt/content/dist/module.mjs setupNitro().
  nitro: {
    preset: 'cloudflare-module',
  },

  vite: {
    optimizeDeps: {
      include: ['tailwindcss/colors'],
    },
  },
  eslint: {
    config: {
      stylistic: true,
    },
  },

  // robots.txt is now generated by @nuxtjs/robots (replaces the old
  // static public/robots.txt) - allow everything, module auto-references
  // the sitemap.
  robots: {
    disallow: [],
  },
})
