// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    // Must precede @nuxt/content: injects the Shiki twoslash transformer
    // that @nuxt/content's MDC renderer picks up for ```ts twoslash fences.
    'nuxt-content-twoslash',
    '@nuxt/content',
    '@nuxt/eslint',
    '@nuxt/image',
    '@nuxt/ui',
    '@vueuse/nuxt',
    '@nuxtjs/sitemap',
    '@nuxtjs/robots',
    'nuxt-og-image',
  ],

  devtools: { enabled: true },

  app: {
    head: {
      titleTemplate: '%s — Neil Richter',
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
      ],
    },
    // Native browser View Transitions API (progressive enhancement - a
    // no-op on browsers without document.startViewTransition, and Nuxt
    // itself skips it automatically when the user has
    // prefers-reduced-motion set). Cross-fades page content on route
    // change; per-element shared transitions (card image -> hero image)
    // are opt-in via view-transition-name in CSS, see
    // app/assets/css/main.css.
    viewTransition: true,
  },

  css: ['~/assets/css/main.css'],

  // Canonical origin - used by @nuxtjs/sitemap, @nuxtjs/robots (sitemap
  // reference), and nuxt-og-image (absolute OG image URLs) to build
  // absolute URLs. www.nook.sh redirects to this apex at the app level
  // (server/middleware/www-redirect.ts), so this is the one true origin.
  site: {
    url: 'https://nook.sh',
  },

  // Baked at build time (not a runtime env read - Cloudflare Workers Builds
  // only exposes these vars to the build step, not to the deployed Worker's
  // runtime). WORKERS_CI_DEFAULT_BRANCH is Cloudflare's own signal for
  // "this build is the production branch" ("true") vs a preview build for
  // any other branch ("false") - see
  // https://developers.cloudflare.com/workers/ci-cd/builds/configuration/#environment-variables
  // Drafts are visible in local `nuxt dev` and on any Cloudflare preview
  // deploy (WORKERS_CI_DEFAULT_BRANCH unset or "false"), hidden only once
  // it's explicitly "true" (a real production build) - see
  // content.config.ts for the always-on sitemap exclusion, and
  // app/pages/{blog,posts/[...slug],projects/index,projects/[...slug]}.vue
  // for where this flag is consumed.
  runtimeConfig: {
    public: {
      showDrafts: process.env.WORKERS_CI_DEFAULT_BRANCH !== 'true',
    },
  },

  // app.viewTransition above only sets the *runtime* enabled flag - the
  // client plugin that actually calls document.startViewTransition on
  // navigation is only registered at build time when this experimental
  // flag is also set (confirmed by reading Nuxt's own module registration
  // logic, node_modules/nuxt/dist/index.mjs: `if
  // (nuxt.options.experimental.viewTransition) addPlugin(...)`). Both are
  // required together, app.viewTransition alone is a silent no-op.
  experimental: {
    viewTransition: true,
  },
  compatibilityDate: '2025-07-15',

  // Deploy target: Cloudflare Workers (unified Workers+static-assets, the
  // current default Cloudflare recommends for new projects - not classic
  // "Pages"). @nuxt/content auto-detects any `cloudflare*` preset and
  // switches its database to Cloudflare D1 (binding name `DB`) regardless
  // of which cloudflare preset is used - no manual database config needed,
  // see node_modules/@nuxt/content/dist/module.mjs setupNitro().
  nitro: {
    preset: 'cloudflare-module',
  },

  vite: {
    optimizeDeps: {
      include: ['tailwindcss/colors'],
    },
  },
  eslint: {
    config: {
      stylistic: true,
    },
  },

  // robots.txt is now generated by @nuxtjs/robots (replaces the old
  // static public/robots.txt) - allow everything, module auto-references
  // the sitemap.
  robots: {
    disallow: [],
  },
})
